#       Licensed to the Apache Software Foundation (ASF) under one
#       or more contributor license agreements.  See the NOTICE file
#       distributed with this work for additional information
#       regarding copyright ownership.  The ASF licenses this file
#       to you under the Apache License, Version 2.0 (the
#       "License"); you may not use this file except in compliance
#       with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing,
#       software distributed under the License is distributed on an
#       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#       KIND, either express or implied.  See the License for the
#       specific language governing permissions and limitations
#       under the License.

language: python
dist: bionic  # Ubuntu 18.04
jobs:
  include:
    - python: "2.7"
      env:
        - PY_LIB_DIR=/usr/lib/python2.7
        - PYSVN_PKG=python-svn
    - python: "3.7"
      env:
        - PY_LIB_DIR=/usr/lib/python3
        - PYSVN_PKG=python3-svn
before_install:
  - sudo apt-get install -qq $PYSVN_PKG libjpeg8-dev zlib1g-dev
install: "pip install -r requirements.txt"
before_script:
  - ls -d $PY_LIB_DIR/dist-packages/pysvn
  - ls -d $VIRTUAL_ENV/lib/python*/site-packages/
  - ln -s $PY_LIB_DIR/dist-packages/pysvn $VIRTUAL_ENV/lib/python*/site-packages/
  - ls $VIRTUAL_ENV/lib/python*/site-packages/pysvn
  - ./rebuild-all.bash
  - npm install
script: ./run_tests
